name: rebuild notebooks

on:
  workflow_dispatch:

jobs:
  notebook_update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
          pip install numpy
          pip install jupyter-book
          
      - name: Build book HTML 
        run: |
          jupyter-book toc from-project .
          jupyter-book build .
          
